### get welcome
GET http://{{host}}:{{port}}/welcome

### get token
GET http://{{host}}:{{port}}/token

> {% //response handler
client.global.set("token", response.body);
client.log("token : " + client.global.get("token"));
%}

### auth
GET http://{{host}}:{{port}}/auth
http-token: {{token}}

### request body test
POST http://{{host}}:{{port}}/body-test
Content-Type: application/json

{
  "key": "myname",
  "value": "jongsang"
}

### request body test from json file
POST http://{{host}}:{{port}}/body-test
Content-Type: application/json

// http 파일과 동일한 패스에 있을 경우
< ./body-test.json



### upload file test
// @no-log
POST http://{{host}}:{{port}}/upload HTTP/1.1
Content-Type: multipart/form-data; boundary=boundary

--boundary
Content-Disposition: form-data; name="file"; filename="upload-test.txt"
Content-Type: text/plain

< ./upload-test.txt


### upload image file test
// @no-log
POST http://{{host}}:{{port}}/upload HTTP/1.1
Content-Type: multipart/form-data; boundary=boundary

--boundary
Content-Disposition: form-data; name="file"; filename="intellij-idea.png"
Content-Type: image/png

< ./intellij-idea.png